definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  user__page:
    weight: -46
    menu_name: home
    parent: ''
    expanded: false
    enabled: true
  user__logout:
    weight: -45
    menu_name: home
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: true
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
